apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  tolerations:
  - key: "tier"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"
  containers:
  - image: nginx
    name: nginx
    resources: {}
  -
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
