apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: data-sharing
    emptyDir: {}
  initContainers:
  - image: busybox
    name: busy1
    command: ["/bin/sh","-c","echo 'Test' > /work-dir/index.html; sleep 60;"]
    volumeMounts:
    - name: data-sharing
      mountPath: /work-dir
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: data-sharing
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
