apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: two-containers
  name: two-containers
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busy1
    resources: {}
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busy2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
