apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  containers:
  - command: ["/bin/sh", "-c"]
    args:
      - echo starting;
        i=0;
        while true;
        do echo "$i -- $(wget -O- 10.100.126.199:6262)"; 
        i=$((i+1));
        sleep 1;
        done;
    # uses the Service IP to connect to different pods in the deployment
    # alternatively use the service name --> wget -O- foo:6262
    image: busybox
    name: busy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
