apiVersion: v1
kind: LimitRange
metadata:
  name: ns-memory-limit
  namespace: limits
spec:
  limits:
  - max: # max and min define the limit range
      memory: "500Mi"
    min:
      memory: "100Mi"
    type: Pod