apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busybox
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busybox
    spec:
      activeDeadlineSeconds: 17
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - echo hello;sleep 30;echo world
            image: busybox
            name: busybox
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
