apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
      - name: the-secret
        valueFrom:
          secretKeyRef:
            name: ext-service-secret
            key: API_KEY
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
