apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: secret-ops
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: secret-volume 
      mountPath: /var/app
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
